name: call out from another repo # name of the workflow 

# This defines the event that triggers the workflow
on: [push] # triggeres 

jobs:
  feature-pipeline:
    uses: asifali-shaik/workflows/.github/workflows/nodejsfeaturepipeline.yaml@main
    with:
      project : 'git-hub'
      component: 'user'
      envrionment: 'dev'