name: nodejs-feature-actions # name of the workflow 

# This defines the event that triggers the workflow
on: workflow_dispatch # triggeres 

jobs:
  # Job name
  catalogue-dev-pipeline:
    runs-on: self-hosted #  hosted runners
    steps:
      - name: check out code 
        uses: actions/checkout@v6

      - name: list the files
        run: ls -la 

      - name: Read version from package.json
        id: package_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: version of package.json
        run : echo "$VERSION"

      - name: install dependences
        run: npm install 

      - name: unit-tests
        run: npm test

      - name: Ensure unzip is installed
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: sonar_scanner
        id: sonar
        uses: actions/checkout@v6
        with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
         fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.1 # Ex: v4.1.0 or sha1, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_URL: ${{ vars.SONAR_URL }}
        
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_URL }} #OPTIONAL
